.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

before_script:
  - dotnet restore

uptool:
  extends:
  - .shared_windows_runners
  stage: deploy
  script: |
    mkdir .\build
    mkdir .\build\gui
    mkdir .\build\cli
    cd SmaliPatcher
    dotnet publish -o ..\build\gui -c Release
    cd ..\SmaliPatcherMin
    dotnet publish -o ..\build\cli -c Release
  artifacts:
    paths:
      - build
  only:
    - master
