.shared_windows_runners:
  tags:
  - shared-windows
  - windows
  - windows-1809

before_script:
  - dotnet restore

uptool:
  extends:
  - .shared_windows_runners
  stage: deploy
  script: |
    mkdir .\build
    dotnet publish -o .\build -c Release
  artifacts:
    paths:
      - build
  only:
    - master
