windows:
  tags:
  - windows
  stage: deploy
  script: |
    mkdir .\build
    mkdir .\build\gui
    mkdir .\build\cli
    cd SmaliPatcher
    dotnet publish -o ..\build\gui -c Release
    cd ..\SmaliPatcherMin
    dotnet publish -o ..\build\cli -c Release
  artifacts:
    paths:
      - build
  only:
    - master

linux:
  tags:
    - docker
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  script: |
    mkdir ./build
    mkdir ./build/cli
    cd ./SmaliPatcherMin
    dotnet publish -o ../build/cli -c Release
  artifacts:
    paths:
      - build
  only:
    - master

android:
  tags:
    - docker
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  script: |
    mkdir ./smp
    cd ./SmaliPatcherMin
    dotnet publish -r android.21-arm64 -o ../smp -c Release --self-contained true -p:DefineConstants="ANDROID_NATIVE"
  artifacts:
    paths:
      - smp
  only:
    - master