# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  image: debian:stable
  stage: deploy
  script:
    - apt update
    - apt install zip -y
    - zip -r source.zip ./*
    - mkdir public
    - cp source.zip public/
  artifacts:
    paths:
      - public
  only:
    - master
